INSERT INTO `skill` VALUES (1, ' 学术写作', 7);
INSERT INTO `skill` VALUES (2, ' 翻译', 8);
INSERT INTO `skill` VALUES (3, ' 英语（美国）', 11);
INSERT INTO `skill` VALUES (4, ' 电器安装', 13);
INSERT INTO `skill` VALUES (5, ' 商业分析', 3);
INSERT INTO `skill` VALUES (6, ' 财务', 13);
INSERT INTO `skill` VALUES (7, ' 批发市场', 12);
INSERT INTO `skill` VALUES (8, ' AJAX', 10);
INSERT INTO `skill` VALUES (9, ' 编辑', 11);
INSERT INTO `skill` VALUES (10, ' Objective C', 7);
INSERT INTO `skill` VALUES (11, ' iPhone', 4);
INSERT INTO `skill` VALUES (12, ' Java', 7);
INSERT INTO `skill` VALUES (13, ' 低功耗蓝牙（BLE）', 2);
INSERT INTO `skill` VALUES (14, ' HTML5', 4);
INSERT INTO `skill` VALUES (15, ' 动画', 13);
INSERT INTO `skill` VALUES (16, ' 内容写作', 1);
INSERT INTO `skill` VALUES (17, ' Article Writing', 13);
INSERT INTO `skill` VALUES (18, ' 博客', 8);
INSERT INTO `skill` VALUES (19, ' 简体中文（中国）', 1);
INSERT INTO `skill` VALUES (20, ' 报告写作', 13);
INSERT INTO `skill` VALUES (21, ' Solidworks', 12);
INSERT INTO `skill` VALUES (22, ' AutoCAD', 6);
INSERT INTO `skill` VALUES (23, ' 横幅设计', 9);
INSERT INTO `skill` VALUES (24, ' 自由职业', 7);
INSERT INTO `skill` VALUES (25, ' C 编程', 7);
INSERT INTO `skill` VALUES (26, ' C# 编程', 11);
INSERT INTO `skill` VALUES (27, ' C++编程', 13);
INSERT INTO `skill` VALUES (28, ' 计算机图形', 13);
INSERT INTO `skill` VALUES (29, ' Adobe Flash', 10);
INSERT INTO `skill` VALUES (30, ' Mac 操作系统', 13);
INSERT INTO `skill` VALUES (31, ' 雇用法', 4);
INSERT INTO `skill` VALUES (32, ' 写书', 8);
INSERT INTO `skill` VALUES (33, ' 校对', 10);
INSERT INTO `skill` VALUES (34, ' 文案写作', 9);
INSERT INTO `skill` VALUES (35, ' 编剧', 8);
INSERT INTO `skill` VALUES (36, ' 产品描述', 12);
INSERT INTO `skill` VALUES (37, ' CUDA', 8);
INSERT INTO `skill` VALUES (38, ' Nginx', 8);
INSERT INTO `skill` VALUES (39, ' OpenGL', 2);
INSERT INTO `skill` VALUES (40, ' Linux', 12);
INSERT INTO `skill` VALUES (41, ' 网络安全', 3);
INSERT INTO `skill` VALUES (42, ' 视窗桌面', 4);
INSERT INTO `skill` VALUES (43, ' 文学写作', 1);
INSERT INTO `skill` VALUES (44, ' 企业资源规划', 11);
INSERT INTO `skill` VALUES (45, ' CSS', 6);
INSERT INTO `skill` VALUES (46, ' 数据输入', 3);
INSERT INTO `skill` VALUES (47, ' Excel', 1);
INSERT INTO `skill` VALUES (48, ' 数据处理', 3);
INSERT INTO `skill` VALUES (49, ' 打字复印', 6);
INSERT INTO `skill` VALUES (50, ' 数据挖掘', 10);
INSERT INTO `skill` VALUES (51, ' 网页搜索', 2);
INSERT INTO `skill` VALUES (52, ' 市场调研', 13);
INSERT INTO `skill` VALUES (53, ' 微软', 12);
INSERT INTO `skill` VALUES (54, ' 3D 渲染', 3);
INSERT INTO `skill` VALUES (55, ' 印度尼西亚语', 6);
INSERT INTO `skill` VALUES (56, ' 韩语', 6);
INSERT INTO `skill` VALUES (57, ' 意大利语', 6);
INSERT INTO `skill` VALUES (58, ' 芬兰语', 10);
INSERT INTO `skill` VALUES (59, ' 挪威语', 2);
INSERT INTO `skill` VALUES (60, ' 希腊语', 10);
INSERT INTO `skill` VALUES (61, ' 德语', 6);
INSERT INTO `skill` VALUES (62, ' 葡萄牙语', 7);
INSERT INTO `skill` VALUES (63, ' 项目管理', 13);
INSERT INTO `skill` VALUES (64, ' Powerpoint', 8);
INSERT INTO `skill` VALUES (65, ' 谷歌 Plus', 6);
INSERT INTO `skill` VALUES (66, ' 社交网络', 8);
INSERT INTO `skill` VALUES (67, ' 社交媒体营销', 4);
INSERT INTO `skill` VALUES (68, ' 金融市场', 5);
INSERT INTO `skill` VALUES (69, ' PSD2CMS', 9);
INSERT INTO `skill` VALUES (70, ' 公共关系', 4);
INSERT INTO `skill` VALUES (71, ' 3D建模', 4);
INSERT INTO `skill` VALUES (72, ' 代笔', 5);
INSERT INTO `skill` VALUES (73, ' 电子书', 13);
INSERT INTO `skill` VALUES (74, ' 影视特效', 9);
INSERT INTO `skill` VALUES (75, ' 平面设计', 11);
INSERT INTO `skill` VALUES (76, ' 企业形象', 10);
INSERT INTO `skill` VALUES (77, ' 图标设计', 1);
INSERT INTO `skill` VALUES (78, ' Logo设计', 3);
INSERT INTO `skill` VALUES (79, ' Photoshop', 8);
INSERT INTO `skill` VALUES (80, ' HTML', 4);
INSERT INTO `skill` VALUES (81, ' 商城', 10);
INSERT INTO `skill` VALUES (82, ' 用户接口 / IA', 9);
INSERT INTO `skill` VALUES (83, ' MySQL', 12);
INSERT INTO `skill` VALUES (84, ' 时尚模特', 3);
INSERT INTO `skill` VALUES (85, ' 安卓', 8);
INSERT INTO `skill` VALUES (86, ' 网站设计', 8);
INSERT INTO `skill` VALUES (87, ' ASP', 5);
INSERT INTO `skill` VALUES (88, ' 网络营销', 12);
INSERT INTO `skill` VALUES (89, ' 市场', 6);
INSERT INTO `skill` VALUES (90, ' Link Building', 13);
INSERT INTO `skill` VALUES (91, ' eBay', 2);
INSERT INTO `skill` VALUES (92, ' 一切', 13);
INSERT INTO `skill` VALUES (93, ' 日语', 9);
INSERT INTO `skill` VALUES (94, ' 电子商务', 11);
INSERT INTO `skill` VALUES (95, ' Cocoa', 1);
INSERT INTO `skill` VALUES (96, ' JavaScript', 1);
INSERT INTO `skill` VALUES (97, ' Python', 8);
INSERT INTO `skill` VALUES (98, ' Oracle', 11);
INSERT INTO `skill` VALUES (99, ' 嵌入式软件', 11);
INSERT INTO `skill` VALUES (100, ' 名片设计', 3);
INSERT INTO `skill` VALUES (101, ' 产品设计', 6);
INSERT INTO `skill` VALUES (102, ' Logistics', 6);
INSERT INTO `skill` VALUES (103, ' 销售', 6);
INSERT INTO `skill` VALUES (104, ' 微软Access', 6);
INSERT INTO `skill` VALUES (105, ' 移动应用开发', 7);
INSERT INTO `skill` VALUES (106, ' J2EE', 1);
INSERT INTO `skill` VALUES (107, ' jQuery / Prototype', 13);
INSERT INTO `skill` VALUES (108, ' iPad', 4);
INSERT INTO `skill` VALUES (109, ' VoIP', 4);
INSERT INTO `skill` VALUES (110, ' Ruby on Rails', 13);
INSERT INTO `skill` VALUES (111, ' Swift', 10);
INSERT INTO `skill` VALUES (112, ' Photoshop 设计', 8);
INSERT INTO `skill` VALUES (113, ' Bitcoin', 4);
INSERT INTO `skill` VALUES (114, ' Drupal', 4);
INSERT INTO `skill` VALUES (115, ' Magento', 13);
INSERT INTO `skill` VALUES (116, ' PHP', 3);
INSERT INTO `skill` VALUES (117, ' 软件构架', 6);
INSERT INTO `skill` VALUES (118, ' 谷歌浏览器', 2);
INSERT INTO `skill` VALUES (119, ' Joomla', 2);
INSERT INTO `skill` VALUES (120, ' 工程', 4);
INSERT INTO `skill` VALUES (121, ' PayPal API', 7);
INSERT INTO `skill` VALUES (122, ' 谷歌地图API', 12);
INSERT INTO `skill` VALUES (123, ' 谷歌分析', 1);
INSERT INTO `skill` VALUES (124, ' node.js', 2);
INSERT INTO `skill` VALUES (125, ' 繁体中文（香港）', 7);
INSERT INTO `skill` VALUES (126, ' 生产', 5);
INSERT INTO `skill` VALUES (127, ' 销售线索', 9);
INSERT INTO `skill` VALUES (128, ' 社会化引擎', 5);
INSERT INTO `skill` VALUES (129, ' 矩阵及数学软件', 6);
INSERT INTO `skill` VALUES (130, ' PLC 与 SCADA', 1);
INSERT INTO `skill` VALUES (131, ' 软件营销应用开发', 1);
INSERT INTO `skill` VALUES (132, ' 软件测试', 12);
INSERT INTO `skill` VALUES (133, ' 法语', 12);
INSERT INTO `skill` VALUES (134, ' 繁体中文（台湾）', 7);
INSERT INTO `skill` VALUES (135, ' 客户服务', 8);
INSERT INTO `skill` VALUES (136, ' 历史', 5);
INSERT INTO `skill` VALUES (137, ' 推特', 8);
INSERT INTO `skill` VALUES (138, ' 摄像', 2);
INSERT INTO `skill` VALUES (139, ' 虚拟助手', 6);
INSERT INTO `skill` VALUES (140, ' 思科', 10);
INSERT INTO `skill` VALUES (141, ' SEO', 8);
INSERT INTO `skill` VALUES (142, ' PSD转化为HTML', 3);
INSERT INTO `skill` VALUES (143, ' ISO9001', 9);
INSERT INTO `skill` VALUES (144, ' 网站测试', 11);
INSERT INTO `skill` VALUES (145, '英语（英国）', 3);
INSERT INTO `skill` VALUES (146, '学术写作', 7);
INSERT INTO `skill` VALUES (147, '文章重写', 8);
INSERT INTO `skill` VALUES (148, '会计', 10);
INSERT INTO `skill` VALUES (149, '广告设计', 2);
INSERT INTO `skill` VALUES (150, '广告', 11);
INSERT INTO `skill` VALUES (151, '.NET', 13);
INSERT INTO `skill` VALUES (152, '安卓', 2);
INSERT INTO `skill` VALUES (153, 'Java', 3);
INSERT INTO `skill` VALUES (154, 'Adobe Flash', 2);
INSERT INTO `skill` VALUES (155, '文章提交', 2);
INSERT INTO `skill` VALUES (156, 'Article Writing', 3);
INSERT INTO `skill` VALUES (157, '音频服务', 3);
INSERT INTO `skill` VALUES (158, 'AutoCAD', 10);
INSERT INTO `skill` VALUES (159, '3ds Max', 9);
INSERT INTO `skill` VALUES (160, '博客', 3);
INSERT INTO `skill` VALUES (161, '批发市场', 8);
INSERT INTO `skill` VALUES (162, '商业计划', 10);
INSERT INTO `skill` VALUES (163, '买方采购', 3);
INSERT INTO `skill` VALUES (164, '阿帕奇', 10);
INSERT INTO `skill` VALUES (165, 'C 编程', 8);
INSERT INTO `skill` VALUES (166, 'Arduino', 13);
INSERT INTO `skill` VALUES (167, 'C# 编程', 11);
INSERT INTO `skill` VALUES (168, 'CAD/CAM', 7);
INSERT INTO `skill` VALUES (169, '漫画 与 卡通', 1);
INSERT INTO `skill` VALUES (170, 'Cocoa', 4);
INSERT INTO `skill` VALUES (171, '内容写作', 8);
INSERT INTO `skill` VALUES (172, '合同', 10);
INSERT INTO `skill` VALUES (173, '文案写作', 11);
INSERT INTO `skill` VALUES (174, '写书', 11);
INSERT INTO `skill` VALUES (175, '封面 与 包装', 11);
INSERT INTO `skill` VALUES (176, 'C++编程', 10);
INSERT INTO `skill` VALUES (177, '宣传字句', 2);
INSERT INTO `skill` VALUES (178, '客户关系管理', 1);
INSERT INTO `skill` VALUES (179, '引导程序', 6);
INSERT INTO `skill` VALUES (180, 'CSS', 10);
INSERT INTO `skill` VALUES (181, 'AJAX', 1);
INSERT INTO `skill` VALUES (182, 'Adobe Dreamweaver', 4);
INSERT INTO `skill` VALUES (183, '数据输入', 10);
INSERT INTO `skill` VALUES (184, '打字复印', 8);
INSERT INTO `skill` VALUES (185, '业务流程外包', 13);
INSERT INTO `skill` VALUES (186, 'PHP', 10);
INSERT INTO `skill` VALUES (187, '数据处理', 10);
INSERT INTO `skill` VALUES (188, '数据挖掘', 8);
INSERT INTO `skill` VALUES (189, 'Drupal', 11);
INSERT INTO `skill` VALUES (190, 'eBay', 12);
INSERT INTO `skill` VALUES (191, '电子商务', 12);
INSERT INTO `skill` VALUES (192, '编辑', 8);
INSERT INTO `skill` VALUES (193, '电子邮箱营销', 1);
INSERT INTO `skill` VALUES (194, '工程', 3);
INSERT INTO `skill` VALUES (195, '3D建模', 2);
INSERT INTO `skill` VALUES (196, '英语（美国）', 9);
INSERT INTO `skill` VALUES (197, '阿拉伯语', 8);
INSERT INTO `skill` VALUES (198, '丹麦语', 11);
INSERT INTO `skill` VALUES (199, '荷兰语', 1);
INSERT INTO `skill` VALUES (200, 'Erlang', 11);
INSERT INTO `skill` VALUES (201, 'Excel', 5);
INSERT INTO `skill` VALUES (202, '企业资源规划', 2);
INSERT INTO `skill` VALUES (203, 'Facebook营销', 4);
INSERT INTO `skill` VALUES (204, '金融研究', 7);
INSERT INTO `skill` VALUES (205, '财务分析', 1);
INSERT INTO `skill` VALUES (206, 'ActionScript', 1);
INSERT INTO `skill` VALUES (207, 'Flex', 4);
INSERT INTO `skill` VALUES (208, '自由职业', 1);
INSERT INTO `skill` VALUES (209, '3D动画', 5);
INSERT INTO `skill` VALUES (210, '游戏设计', 9);
INSERT INTO `skill` VALUES (211, '地理位置', 8);
INSERT INTO `skill` VALUES (212, '电子书', 6);
INSERT INTO `skill` VALUES (213, '横幅设计', 9);
INSERT INTO `skill` VALUES (214, '宣传册设计', 5);
INSERT INTO `skill` VALUES (215, '名片设计', 12);
INSERT INTO `skill` VALUES (216, '传单设计', 7);
INSERT INTO `skill` VALUES (217, '平面设计', 2);
INSERT INTO `skill` VALUES (218, 'HTML', 2);
INSERT INTO `skill` VALUES (219, 'Joomla', 6);
INSERT INTO `skill` VALUES (220, '时尚设计', 1);
INSERT INTO `skill` VALUES (221, '3D 设计', 1);
INSERT INTO `skill` VALUES (222, 'Codeigniter', 3);
INSERT INTO `skill` VALUES (223, '工艺美术', 13);
INSERT INTO `skill` VALUES (224, '企业形象', 8);
INSERT INTO `skill` VALUES (225, '主页设计', 12);
INSERT INTO `skill` VALUES (226, 'HTML5', 1);
INSERT INTO `skill` VALUES (227, '品牌推广', 7);
INSERT INTO `skill` VALUES (228, '网络营销', 4);
INSERT INTO `skill` VALUES (229, '教育与辅导', 5);
INSERT INTO `skill` VALUES (230, '谷歌Adwords', 5);
INSERT INTO `skill` VALUES (231, '一切', 11);
INSERT INTO `skill` VALUES (232, 'iPad', 1);
INSERT INTO `skill` VALUES (233, 'iPhone', 10);
INSERT INTO `skill` VALUES (234, 'ISO9001', 12);
INSERT INTO `skill` VALUES (235, 'JavaScript', 12);
INSERT INTO `skill` VALUES (236, 'Linux', 10);
INSERT INTO `skill` VALUES (237, '电子', 10);
INSERT INTO `skill` VALUES (238, 'Logo设计', 13);
INSERT INTO `skill` VALUES (239, '创意设计', 2);
INSERT INTO `skill` VALUES (240, 'Magento', 8);
INSERT INTO `skill` VALUES (241, '生产', 13);
INSERT INTO `skill` VALUES (242, '市场调研', 7);
INSERT INTO `skill` VALUES (243, '销售线索', 13);
INSERT INTO `skill` VALUES (244, '市场', 11);
INSERT INTO `skill` VALUES (245, '微软Access', 5);
INSERT INTO `skill` VALUES (246, '微软', 12);
INSERT INTO `skill` VALUES (247, 'CakePHP', 1);
INSERT INTO `skill` VALUES (248, 'J2EE', 7);
INSERT INTO `skill` VALUES (249, 'MySQL', 5);
INSERT INTO `skill` VALUES (250, 'ASP.NET', 8);
INSERT INTO `skill` VALUES (251, 'Mac 操作系统', 8);
INSERT INTO `skill` VALUES (252, 'Objective C', 11);
INSERT INTO `skill` VALUES (253, '印制板布局', 8);
INSERT INTO `skill` VALUES (254, '摄影', 5);
INSERT INTO `skill` VALUES (255, 'Photoshop', 11);
INSERT INTO `skill` VALUES (256, '影视特效', 8);
INSERT INTO `skill` VALUES (257, '数据库管理', 8);
INSERT INTO `skill` VALUES (258, 'ASP', 6);
INSERT INTO `skill` VALUES (259, '苹果Safari浏览器', 1);
INSERT INTO `skill` VALUES (260, 'CMS', 7);
INSERT INTO `skill` VALUES (261, '地图学与地图', 6);
INSERT INTO `skill` VALUES (262, 'Appcelerator Titanium', 4);
INSERT INTO `skill` VALUES (263, 'Powerpoint', 10);
INSERT INTO `skill` VALUES (264, 'Prestashop', 1);
INSERT INTO `skill` VALUES (265, '产品设计', 11);
INSERT INTO `skill` VALUES (266, '项目管理', 2);
INSERT INTO `skill` VALUES (267, 'PSD转化为HTML', 3);
INSERT INTO `skill` VALUES (268, 'Python', 5);
INSERT INTO `skill` VALUES (269, '招募', 3);
INSERT INTO `skill` VALUES (270, '研究', 3);
INSERT INTO `skill` VALUES (271, 'Logistics', 1);
INSERT INTO `skill` VALUES (272, '销售', 4);
INSERT INTO `skill` VALUES (273, '脚本安装', 11);
INSERT INTO `skill` VALUES (274, 'SEO', 5);
INSERT INTO `skill` VALUES (275, '简体中文（中国）', 13);
INSERT INTO `skill` VALUES (276, '软件构架', 12);
INSERT INTO `skill` VALUES (277, '软件测试', 9);
INSERT INTO `skill` VALUES (278, 'SQL', 13);
INSERT INTO `skill` VALUES (279, '供应商采购', 8);
INSERT INTO `skill` VALUES (280, '电话销售', 10);
INSERT INTO `skill` VALUES (281, '韩语', 7);
INSERT INTO `skill` VALUES (282, '技术写作', 3);
INSERT INTO `skill` VALUES (283, '翻译', 7);
INSERT INTO `skill` VALUES (284, '英语语法', 5);
INSERT INTO `skill` VALUES (285, '意大利语', 5);
INSERT INTO `skill` VALUES (286, '捷克语', 10);
INSERT INTO `skill` VALUES (287, '社交网络', 1);
INSERT INTO `skill` VALUES (288, 'Unity 3D', 5);
INSERT INTO `skill` VALUES (289, '用户体验设计', 10);
INSERT INTO `skill` VALUES (290, 'VB.NET', 3);
INSERT INTO `skill` VALUES (291, '视频服务', 5);
INSERT INTO `skill` VALUES (292, '客户支持', 8);
INSERT INTO `skill` VALUES (293, '虚拟助手', 6);
INSERT INTO `skill` VALUES (294, 'Visual Basic', 7);
INSERT INTO `skill` VALUES (295, '配音演员', 2);
INSERT INTO `skill` VALUES (296, '网页搜罗', 8);
INSERT INTO `skill` VALUES (297, '网页搜索', 8);
INSERT INTO `skill` VALUES (298, '网络主机', 13);
INSERT INTO `skill` VALUES (299, '论坛软件', 9);
INSERT INTO `skill` VALUES (300, 'CS-Cart', 4);
INSERT INTO `skill` VALUES (301, '网站设计', 10);
INSERT INTO `skill` VALUES (302, '视窗 Server', 2);
INSERT INTO `skill` VALUES (303, 'Word 处理', 12);
INSERT INTO `skill` VALUES (304, '动画', 3);
INSERT INTO `skill` VALUES (305, '简体中文（中国）', 4);
INSERT INTO `skill` VALUES (306, '学术写作', 6);
INSERT INTO `skill` VALUES (307, '翻译', 8);
INSERT INTO `skill` VALUES (308, 'Logistics', 12);
INSERT INTO `skill` VALUES (309, '商业计划', 12);
INSERT INTO `skill` VALUES (310, 'Intuit快账', 3);
INSERT INTO `skill` VALUES (311, 'C# 编程', 11);
INSERT INTO `skill` VALUES (312, '发布', 12);
INSERT INTO `skill` VALUES (313, 'VoIP', 1);
INSERT INTO `skill` VALUES (314, '视频服务', 5);
INSERT INTO `skill` VALUES (315, 'iPhone', 5);
INSERT INTO `skill` VALUES (316, 'MySQL', 9);
INSERT INTO `skill` VALUES (317, '漫画 与 卡通', 5);
INSERT INTO `skill` VALUES (318, '文案写作', 6);
INSERT INTO `skill` VALUES (319, '论坛发贴', 7);
INSERT INTO `skill` VALUES (320, '代笔', 12);
INSERT INTO `skill` VALUES (321, '校对', 12);
INSERT INTO `skill` VALUES (322, '内容写作', 13);
INSERT INTO `skill` VALUES (323, '研究', 13);
INSERT INTO `skill` VALUES (324, '系统管理', 10);
INSERT INTO `skill` VALUES (325, 'C++编程', 10);
INSERT INTO `skill` VALUES (326, 'Linux', 7);
INSERT INTO `skill` VALUES (327, '电子', 7);
INSERT INTO `skill` VALUES (328, '机器学习（ML）', 3);
INSERT INTO `skill` VALUES (329, 'C 编程', 12);
INSERT INTO `skill` VALUES (330, 'Golang', 8);
INSERT INTO `skill` VALUES (331, '微软', 6);
INSERT INTO `skill` VALUES (332, 'Objective C', 8);
INSERT INTO `skill` VALUES (333, '时尚设计', 10);
INSERT INTO `skill` VALUES (334, '法律', 2);
INSERT INTO `skill` VALUES (335, '电子书', 12);
INSERT INTO `skill` VALUES (336, '视频传播', 1);
INSERT INTO `skill` VALUES (337, 'Red Hat', 9);
INSERT INTO `skill` VALUES (338, '标语', 10);
INSERT INTO `skill` VALUES (339, 'Drupal', 4);
INSERT INTO `skill` VALUES (340, 'JavaScript', 11);
INSERT INTO `skill` VALUES (341, 'HTML5', 2);
INSERT INTO `skill` VALUES (342, 'AJAX', 7);
INSERT INTO `skill` VALUES (343, '数据处理', 3);
INSERT INTO `skill` VALUES (344, 'Excel', 8);
INSERT INTO `skill` VALUES (345, '数据输入', 4);
INSERT INTO `skill` VALUES (346, '网页搜罗', 5);
INSERT INTO `skill` VALUES (347, '网页搜索', 5);
INSERT INTO `skill` VALUES (348, '工程', 11);
INSERT INTO `skill` VALUES (349, '俄语', 5);
INSERT INTO `skill` VALUES (350, '西班牙语', 8);
INSERT INTO `skill` VALUES (351, '视频制作', 13);
INSERT INTO `skill` VALUES (352, 'Word', 10);
INSERT INTO `skill` VALUES (353, 'Pinterest', 7);
INSERT INTO `skill` VALUES (354, '社交网络', 3);
INSERT INTO `skill` VALUES (355, '电子邮箱营销', 11);
INSERT INTO `skill` VALUES (356, '金融研究', 2);
INSERT INTO `skill` VALUES (357, '3D 渲染', 1);
INSERT INTO `skill` VALUES (358, '安卓', 11);
INSERT INTO `skill` VALUES (359, '封面 与 包装', 12);
INSERT INTO `skill` VALUES (360, 'Logo设计', 5);
INSERT INTO `skill` VALUES (361, 'Photoshop 设计', 12);
INSERT INTO `skill` VALUES (362, 'PHP', 12);
INSERT INTO `skill` VALUES (363, 'Joomla', 6);
INSERT INTO `skill` VALUES (364, '用户接口 / IA', 11);
INSERT INTO `skill` VALUES (365, '微软Access', 6);
INSERT INTO `skill` VALUES (366, '网站设计', 9);
INSERT INTO `skill` VALUES (367, 'Photoshop', 7);
INSERT INTO `skill` VALUES (368, 'HTML', 13);
INSERT INTO `skill` VALUES (369, '平面设计', 3);
INSERT INTO `skill` VALUES (370, 'node.js', 5);
INSERT INTO `skill` VALUES (371, 'JSP', 3);
INSERT INTO `skill` VALUES (372, 'Java', 5);
INSERT INTO `skill` VALUES (373, '视频编辑', 1);
INSERT INTO `skill` VALUES (374, '网络营销', 7);
INSERT INTO `skill` VALUES (375, 'PSD转化为HTML', 1);
INSERT INTO `skill` VALUES (376, 'Illustration', 9);
INSERT INTO `skill` VALUES (377, 'jQuery / Prototype', 10);
INSERT INTO `skill` VALUES (378, 'Illustrator', 5);
INSERT INTO `skill` VALUES (379, 'ASP', 4);
INSERT INTO `skill` VALUES (380, '数据库编程', 6);
INSERT INTO `skill` VALUES (381, 'Link Building', 12);
INSERT INTO `skill` VALUES (382, '市场', 12);
INSERT INTO `skill` VALUES (383, '销售', 5);
INSERT INTO `skill` VALUES (384, 'SEO', 11);
INSERT INTO `skill` VALUES (385, '销售线索', 2);
INSERT INTO `skill` VALUES (386, '社会化引擎', 13);
INSERT INTO `skill` VALUES (387, 'J2EE', 9);
INSERT INTO `skill` VALUES (388, 'Delphi', 2);
INSERT INTO `skill` VALUES (389, 'UNIX', 13);
INSERT INTO `skill` VALUES (390, '企业形象', 2);
INSERT INTO `skill` VALUES (391, '生产', 10);
INSERT INTO `skill` VALUES (392, '产品采购', 11);
INSERT INTO `skill` VALUES (393, '自由职业', 12);
INSERT INTO `skill` VALUES (394, '移动应用开发', 10);
INSERT INTO `skill` VALUES (395, 'iPad', 3);
INSERT INTO `skill` VALUES (396, '项目管理', 1);
INSERT INTO `skill` VALUES (397, '视窗桌面', 1);
INSERT INTO `skill` VALUES (398, '软件构架', 7);
INSERT INTO `skill` VALUES (399, '软件测试', 12);
INSERT INTO `skill` VALUES (400, '谷歌地图API', 8);
INSERT INTO `skill` VALUES (401, '网络主机', 5);
INSERT INTO `skill` VALUES (402, '电话销售', 6);
INSERT INTO `skill` VALUES (403, '视窗应用程序接口', 2);
INSERT INTO `skill` VALUES (404, 'Visual Basic', 13);
INSERT INTO `skill` VALUES (405, 'Salesforce.com', 4);
INSERT INTO `skill` VALUES (406, '网站测试', 8);
INSERT INTO `skill` VALUES (407, '工艺美术', 3);
INSERT INTO `skill` VALUES (408, '动态图像', 9);
INSERT INTO `skill` VALUES (409, '3ds Max', 2);
INSERT INTO `skill` VALUES (410, 'AutoCAD', 7);
INSERT INTO `skill` VALUES (411, '客户支持', 2);
INSERT INTO `skill` VALUES (412, '网站管理', 5);
INSERT INTO `skill` VALUES (413, 'Jabber', 4);
INSERT INTO `skill` VALUES (414, '购物车', 1);
INSERT INTO `skill` VALUES (415, 'WordPress', 10);
INSERT INTO `skill` VALUES (416, ' Payroll', 4);
INSERT INTO `skill` VALUES (417, ' 移动应用测试', 3);
INSERT INTO `skill` VALUES (418, ' 体育', 10);
INSERT INTO `skill` VALUES (419, ' 微控制器', 8);
INSERT INTO `skill` VALUES (420, ' 游戏设计', 13);
INSERT INTO `skill` VALUES (421, ' SQL', 6);
INSERT INTO `skill` VALUES (422, ' 法律写作', 10);
INSERT INTO `skill` VALUES (423, ' 研究', 9);
INSERT INTO `skill` VALUES (424, ' 视频服务', 13);
INSERT INTO `skill` VALUES (425, ' 网络管理', 2);
INSERT INTO `skill` VALUES (426, ' PhoneGap', 12);
INSERT INTO `skill` VALUES (427, ' ASP.NET', 5);
INSERT INTO `skill` VALUES (428, ' 网页搜罗', 11);
INSERT INTO `skill` VALUES (429, ' 工业设计', 8);
INSERT INTO `skill` VALUES (430, ' 泰语', 6);
INSERT INTO `skill` VALUES (431, ' 土耳其语', 8);
INSERT INTO `skill` VALUES (432, ' 越南语', 2);
INSERT INTO `skill` VALUES (433, ' 瑞士语', 3);
INSERT INTO `skill` VALUES (434, ' Facebook营销', 5);
INSERT INTO `skill` VALUES (435, ' T恤', 1);
INSERT INTO `skill` VALUES (436, ' 网络主机', 2);
INSERT INTO `skill` VALUES (437, ' 摄影', 6);
INSERT INTO `skill` VALUES (438, ' Visual Basic', 2);
INSERT INTO `skill` VALUES (439, ' WordPress', 2);
INSERT INTO `skill` VALUES (440, ' 购物车', 3);
INSERT INTO `skill` VALUES (441, ' Illustrator', 11);
INSERT INTO `skill` VALUES (442, ' JavaFX', 6);
INSERT INTO `skill` VALUES (443, ' VB.NET', 6);
INSERT INTO `skill` VALUES (444, ' 封面 与 包装', 11);
INSERT INTO `skill` VALUES (445, ' 产品采购', 7);
INSERT INTO `skill` VALUES (446, ' 供应商采购', 11);
INSERT INTO `skill` VALUES (447, ' 视窗电话', 5);
INSERT INTO `skill` VALUES (448, ' Maya', 5);
INSERT INTO `skill` VALUES (449, ' 网站管理', 2);
INSERT INTO `skill` VALUES (450, ' 信息图表', 4);
INSERT INTO `skill` VALUES (451, ' UNIX', 6);
INSERT INTO `skill` VALUES (452, ' Unity 3D', 6);
INSERT INTO `skill` VALUES (453, ' 工艺美术', 11);
INSERT INTO `skill` VALUES (454, ' x86/x64 汇编', 11);
INSERT INTO `skill` VALUES (455, ' YouTube', 6);
