INSERT INTO `skill` VALUES (1, ' 学术写作');
INSERT INTO `skill` VALUES (2, ' 翻译');
INSERT INTO `skill` VALUES (3, ' 英语（美国）');
INSERT INTO `skill` VALUES (4, ' 电器安装');
INSERT INTO `skill` VALUES (5, ' 商业分析');
INSERT INTO `skill` VALUES (6, ' 财务');
INSERT INTO `skill` VALUES (7, ' 批发市场');
INSERT INTO `skill` VALUES (8, ' AJAX');
INSERT INTO `skill` VALUES (9, ' 编辑');
INSERT INTO `skill` VALUES (10, ' Objective C');
INSERT INTO `skill` VALUES (11, ' iPhone');
INSERT INTO `skill` VALUES (12, ' Java');
INSERT INTO `skill` VALUES (13, ' 低功耗蓝牙（BLE）');
INSERT INTO `skill` VALUES (14, ' HTML5');
INSERT INTO `skill` VALUES (15, ' 动画');
INSERT INTO `skill` VALUES (16, ' 内容写作');
INSERT INTO `skill` VALUES (17, ' Article Writing');
INSERT INTO `skill` VALUES (18, ' 博客');
INSERT INTO `skill` VALUES (19, ' 简体中文（中国）');
INSERT INTO `skill` VALUES (20, ' 报告写作');
INSERT INTO `skill` VALUES (21, ' Solidworks');
INSERT INTO `skill` VALUES (22, ' AutoCAD');
INSERT INTO `skill` VALUES (23, ' 横幅设计');
INSERT INTO `skill` VALUES (24, ' 自由职业');
INSERT INTO `skill` VALUES (25, ' C 编程');
INSERT INTO `skill` VALUES (26, ' C# 编程');
INSERT INTO `skill` VALUES (27, ' C++编程');
INSERT INTO `skill` VALUES (28, ' 计算机图形');
INSERT INTO `skill` VALUES (29, ' Adobe Flash');
INSERT INTO `skill` VALUES (30, ' Mac 操作系统');
INSERT INTO `skill` VALUES (31, ' 雇用法');
INSERT INTO `skill` VALUES (32, ' 写书');
INSERT INTO `skill` VALUES (33, ' 校对');
INSERT INTO `skill` VALUES (34, ' 文案写作');
INSERT INTO `skill` VALUES (35, ' 编剧');
INSERT INTO `skill` VALUES (36, ' 产品描述');
INSERT INTO `skill` VALUES (37, ' CUDA');
INSERT INTO `skill` VALUES (38, ' Nginx');
INSERT INTO `skill` VALUES (39, ' OpenGL');
INSERT INTO `skill` VALUES (40, ' Linux');
INSERT INTO `skill` VALUES (41, ' 网络安全');
INSERT INTO `skill` VALUES (42, ' 视窗桌面');
INSERT INTO `skill` VALUES (43, ' 文学写作');
INSERT INTO `skill` VALUES (44, ' 企业资源规划');
INSERT INTO `skill` VALUES (45, ' CSS');
INSERT INTO `skill` VALUES (46, ' 数据输入');
INSERT INTO `skill` VALUES (47, ' Excel');
INSERT INTO `skill` VALUES (48, ' 数据处理');
INSERT INTO `skill` VALUES (49, ' 打字复印');
INSERT INTO `skill` VALUES (50, ' 数据挖掘');
INSERT INTO `skill` VALUES (51, ' 网页搜索');
INSERT INTO `skill` VALUES (52, ' 市场调研');
INSERT INTO `skill` VALUES (53, ' 微软');
INSERT INTO `skill` VALUES (54, ' 3D 渲染');
INSERT INTO `skill` VALUES (55, ' 印度尼西亚语');
INSERT INTO `skill` VALUES (56, ' 韩语');
INSERT INTO `skill` VALUES (57, ' 意大利语');
INSERT INTO `skill` VALUES (58, ' 芬兰语');
INSERT INTO `skill` VALUES (59, ' 挪威语');
INSERT INTO `skill` VALUES (60, ' 希腊语');
INSERT INTO `skill` VALUES (61, ' 德语');
INSERT INTO `skill` VALUES (62, ' 葡萄牙语');
INSERT INTO `skill` VALUES (63, ' 项目管理');
INSERT INTO `skill` VALUES (64, ' Powerpoint');
INSERT INTO `skill` VALUES (65, ' 谷歌 Plus');
INSERT INTO `skill` VALUES (66, ' 社交网络');
INSERT INTO `skill` VALUES (67, ' 社交媒体营销');
INSERT INTO `skill` VALUES (68, ' 金融市场');
INSERT INTO `skill` VALUES (69, ' PSD2CMS');
INSERT INTO `skill` VALUES (70, ' 公共关系');
INSERT INTO `skill` VALUES (71, ' 3D建模');
INSERT INTO `skill` VALUES (72, ' 代笔');
INSERT INTO `skill` VALUES (73, ' 电子书');
INSERT INTO `skill` VALUES (74, ' 影视特效');
INSERT INTO `skill` VALUES (75, ' 平面设计');
INSERT INTO `skill` VALUES (76, ' 企业形象');
INSERT INTO `skill` VALUES (77, ' 图标设计');
INSERT INTO `skill` VALUES (78, ' Logo设计');
INSERT INTO `skill` VALUES (79, ' Photoshop');
INSERT INTO `skill` VALUES (80, ' HTML');
INSERT INTO `skill` VALUES (81, ' 商城');
INSERT INTO `skill` VALUES (82, ' 用户接口 / IA');
INSERT INTO `skill` VALUES (83, ' MySQL');
INSERT INTO `skill` VALUES (84, ' 时尚模特');
INSERT INTO `skill` VALUES (85, ' 安卓');
INSERT INTO `skill` VALUES (86, ' 网站设计');
INSERT INTO `skill` VALUES (87, ' ASP');
INSERT INTO `skill` VALUES (88, ' 网络营销');
INSERT INTO `skill` VALUES (89, ' 市场');
INSERT INTO `skill` VALUES (90, ' Link Building');
INSERT INTO `skill` VALUES (91, ' eBay');
INSERT INTO `skill` VALUES (92, ' 一切');
INSERT INTO `skill` VALUES (93, ' 日语');
INSERT INTO `skill` VALUES (94, ' 电子商务');
INSERT INTO `skill` VALUES (95, ' Cocoa');
INSERT INTO `skill` VALUES (96, ' JavaScript');
INSERT INTO `skill` VALUES (97, ' Python');
INSERT INTO `skill` VALUES (98, ' Oracle');
INSERT INTO `skill` VALUES (99, ' 嵌入式软件');
INSERT INTO `skill` VALUES (100, ' 名片设计');
INSERT INTO `skill` VALUES (101, ' 产品设计');
INSERT INTO `skill` VALUES (102, ' Logistics');
INSERT INTO `skill` VALUES (103, ' 销售');
INSERT INTO `skill` VALUES (104, ' 微软Access');
INSERT INTO `skill` VALUES (105, ' 移动应用开发');
INSERT INTO `skill` VALUES (106, ' J2EE');
INSERT INTO `skill` VALUES (107, ' jQuery / Prototype');
INSERT INTO `skill` VALUES (108, ' iPad');
INSERT INTO `skill` VALUES (109, ' VoIP');
INSERT INTO `skill` VALUES (110, ' Ruby on Rails');
INSERT INTO `skill` VALUES (111, ' Swift');
INSERT INTO `skill` VALUES (112, ' Photoshop 设计');
INSERT INTO `skill` VALUES (113, ' Bitcoin');
INSERT INTO `skill` VALUES (114, ' Drupal');
INSERT INTO `skill` VALUES (115, ' Magento');
INSERT INTO `skill` VALUES (116, ' PHP');
INSERT INTO `skill` VALUES (117, ' 软件构架');
INSERT INTO `skill` VALUES (118, ' 谷歌浏览器');
INSERT INTO `skill` VALUES (119, ' Joomla');
INSERT INTO `skill` VALUES (120, ' 工程');
INSERT INTO `skill` VALUES (121, ' PayPal API');
INSERT INTO `skill` VALUES (122, ' 谷歌地图API');
INSERT INTO `skill` VALUES (123, ' 谷歌分析');
INSERT INTO `skill` VALUES (124, ' node.js');
INSERT INTO `skill` VALUES (125, ' 繁体中文（香港）');
INSERT INTO `skill` VALUES (126, ' 生产');
INSERT INTO `skill` VALUES (127, ' 销售线索');
INSERT INTO `skill` VALUES (128, ' 社会化引擎');
INSERT INTO `skill` VALUES (129, ' 矩阵及数学软件');
INSERT INTO `skill` VALUES (130, ' PLC 与 SCADA');
INSERT INTO `skill` VALUES (131, ' 软件营销应用开发');
INSERT INTO `skill` VALUES (132, ' 软件测试');
INSERT INTO `skill` VALUES (133, ' 法语');
INSERT INTO `skill` VALUES (134, ' 繁体中文（台湾）');
INSERT INTO `skill` VALUES (135, ' 客户服务');
INSERT INTO `skill` VALUES (136, ' 历史');
INSERT INTO `skill` VALUES (137, ' 推特');
INSERT INTO `skill` VALUES (138, ' 摄像');
INSERT INTO `skill` VALUES (139, ' 虚拟助手');
INSERT INTO `skill` VALUES (140, ' 思科');
INSERT INTO `skill` VALUES (141, ' SEO');
INSERT INTO `skill` VALUES (142, ' PSD转化为HTML');
INSERT INTO `skill` VALUES (143, ' ISO9001');
INSERT INTO `skill` VALUES (144, ' 网站测试');
INSERT INTO `skill` VALUES (145, '英语（英国）');
INSERT INTO `skill` VALUES (146, '学术写作');
INSERT INTO `skill` VALUES (147, '文章重写');
INSERT INTO `skill` VALUES (148, '会计');
INSERT INTO `skill` VALUES (149, '广告设计');
INSERT INTO `skill` VALUES (150, '广告');
INSERT INTO `skill` VALUES (151, '.NET');
INSERT INTO `skill` VALUES (152, '安卓');
INSERT INTO `skill` VALUES (153, 'Java');
INSERT INTO `skill` VALUES (154, 'Adobe Flash');
INSERT INTO `skill` VALUES (155, '文章提交');
INSERT INTO `skill` VALUES (156, 'Article Writing');
INSERT INTO `skill` VALUES (157, '音频服务');
INSERT INTO `skill` VALUES (158, 'AutoCAD');
INSERT INTO `skill` VALUES (159, '3ds Max');
INSERT INTO `skill` VALUES (160, '博客');
INSERT INTO `skill` VALUES (161, '批发市场');
INSERT INTO `skill` VALUES (162, '商业计划');
INSERT INTO `skill` VALUES (163, '买方采购');
INSERT INTO `skill` VALUES (164, '阿帕奇');
INSERT INTO `skill` VALUES (165, 'C 编程');
INSERT INTO `skill` VALUES (166, 'Arduino');
INSERT INTO `skill` VALUES (167, 'C# 编程');
INSERT INTO `skill` VALUES (168, 'CAD/CAM');
INSERT INTO `skill` VALUES (169, '漫画 与 卡通');
INSERT INTO `skill` VALUES (170, 'Cocoa');
INSERT INTO `skill` VALUES (171, '内容写作');
INSERT INTO `skill` VALUES (172, '合同');
INSERT INTO `skill` VALUES (173, '文案写作');
INSERT INTO `skill` VALUES (174, '写书');
INSERT INTO `skill` VALUES (175, '封面 与 包装');
INSERT INTO `skill` VALUES (176, 'C++编程');
INSERT INTO `skill` VALUES (177, '宣传字句');
INSERT INTO `skill` VALUES (178, '客户关系管理');
INSERT INTO `skill` VALUES (179, '引导程序');
INSERT INTO `skill` VALUES (180, 'CSS');
INSERT INTO `skill` VALUES (181, 'AJAX');
INSERT INTO `skill` VALUES (182, 'Adobe Dreamweaver');
INSERT INTO `skill` VALUES (183, '数据输入');
INSERT INTO `skill` VALUES (184, '打字复印');
INSERT INTO `skill` VALUES (185, '业务流程外包');
INSERT INTO `skill` VALUES (186, 'PHP');
INSERT INTO `skill` VALUES (187, '数据处理');
INSERT INTO `skill` VALUES (188, '数据挖掘');
INSERT INTO `skill` VALUES (189, 'Drupal');
INSERT INTO `skill` VALUES (190, 'eBay');
INSERT INTO `skill` VALUES (191, '电子商务');
INSERT INTO `skill` VALUES (192, '编辑');
INSERT INTO `skill` VALUES (193, '电子邮箱营销');
INSERT INTO `skill` VALUES (194, '工程');
INSERT INTO `skill` VALUES (195, '3D建模');
INSERT INTO `skill` VALUES (196, '英语（美国）');
INSERT INTO `skill` VALUES (197, '阿拉伯语');
INSERT INTO `skill` VALUES (198, '丹麦语');
INSERT INTO `skill` VALUES (199, '荷兰语');
INSERT INTO `skill` VALUES (200, 'Erlang');
INSERT INTO `skill` VALUES (201, 'Excel');
INSERT INTO `skill` VALUES (202, '企业资源规划');
INSERT INTO `skill` VALUES (203, 'Facebook营销');
INSERT INTO `skill` VALUES (204, '金融研究');
INSERT INTO `skill` VALUES (205, '财务分析');
INSERT INTO `skill` VALUES (206, 'ActionScript');
INSERT INTO `skill` VALUES (207, 'Flex');
INSERT INTO `skill` VALUES (208, '自由职业');
INSERT INTO `skill` VALUES (209, '3D动画');
INSERT INTO `skill` VALUES (210, '游戏设计');
INSERT INTO `skill` VALUES (211, '地理位置');
INSERT INTO `skill` VALUES (212, '电子书');
INSERT INTO `skill` VALUES (213, '横幅设计');
INSERT INTO `skill` VALUES (214, '宣传册设计');
INSERT INTO `skill` VALUES (215, '名片设计');
INSERT INTO `skill` VALUES (216, '传单设计');
INSERT INTO `skill` VALUES (217, '平面设计');
INSERT INTO `skill` VALUES (218, 'HTML');
INSERT INTO `skill` VALUES (219, 'Joomla');
INSERT INTO `skill` VALUES (220, '时尚设计');
INSERT INTO `skill` VALUES (221, '3D 设计');
INSERT INTO `skill` VALUES (222, 'Codeigniter');
INSERT INTO `skill` VALUES (223, '工艺美术');
INSERT INTO `skill` VALUES (224, '企业形象');
INSERT INTO `skill` VALUES (225, '主页设计');
INSERT INTO `skill` VALUES (226, 'HTML5');
INSERT INTO `skill` VALUES (227, '品牌推广');
INSERT INTO `skill` VALUES (228, '网络营销');
INSERT INTO `skill` VALUES (229, '教育与辅导');
INSERT INTO `skill` VALUES (230, '谷歌Adwords');
INSERT INTO `skill` VALUES (231, '一切');
INSERT INTO `skill` VALUES (232, 'iPad');
INSERT INTO `skill` VALUES (233, 'iPhone');
INSERT INTO `skill` VALUES (234, 'ISO9001');
INSERT INTO `skill` VALUES (235, 'JavaScript');
INSERT INTO `skill` VALUES (236, 'Linux');
INSERT INTO `skill` VALUES (237, '电子');
INSERT INTO `skill` VALUES (238, 'Logo设计');
INSERT INTO `skill` VALUES (239, '创意设计');
INSERT INTO `skill` VALUES (240, 'Magento');
INSERT INTO `skill` VALUES (241, '生产');
INSERT INTO `skill` VALUES (242, '市场调研');
INSERT INTO `skill` VALUES (243, '销售线索');
INSERT INTO `skill` VALUES (244, '市场');
INSERT INTO `skill` VALUES (245, '微软Access');
INSERT INTO `skill` VALUES (246, '微软');
INSERT INTO `skill` VALUES (247, 'CakePHP');
INSERT INTO `skill` VALUES (248, 'J2EE');
INSERT INTO `skill` VALUES (249, 'MySQL');
INSERT INTO `skill` VALUES (250, 'ASP.NET');
INSERT INTO `skill` VALUES (251, 'Mac 操作系统');
INSERT INTO `skill` VALUES (252, 'Objective C');
INSERT INTO `skill` VALUES (253, '印制板布局');
INSERT INTO `skill` VALUES (254, '摄影');
INSERT INTO `skill` VALUES (255, 'Photoshop');
INSERT INTO `skill` VALUES (256, '影视特效');
INSERT INTO `skill` VALUES (257, '数据库管理');
INSERT INTO `skill` VALUES (258, 'ASP');
INSERT INTO `skill` VALUES (259, '苹果Safari浏览器');
INSERT INTO `skill` VALUES (260, 'CMS');
INSERT INTO `skill` VALUES (261, '地图学与地图');
INSERT INTO `skill` VALUES (262, 'Appcelerator Titanium');
INSERT INTO `skill` VALUES (263, 'Powerpoint');
INSERT INTO `skill` VALUES (264, 'Prestashop');
INSERT INTO `skill` VALUES (265, '产品设计');
INSERT INTO `skill` VALUES (266, '项目管理');
INSERT INTO `skill` VALUES (267, 'PSD转化为HTML');
INSERT INTO `skill` VALUES (268, 'Python');
INSERT INTO `skill` VALUES (269, '招募');
INSERT INTO `skill` VALUES (270, '研究');
INSERT INTO `skill` VALUES (271, 'Logistics');
INSERT INTO `skill` VALUES (272, '销售');
INSERT INTO `skill` VALUES (273, '脚本安装');
INSERT INTO `skill` VALUES (274, 'SEO');
INSERT INTO `skill` VALUES (275, '简体中文（中国）');
INSERT INTO `skill` VALUES (276, '软件构架');
INSERT INTO `skill` VALUES (277, '软件测试');
INSERT INTO `skill` VALUES (278, 'SQL');
INSERT INTO `skill` VALUES (279, '供应商采购');
INSERT INTO `skill` VALUES (280, '电话销售');
INSERT INTO `skill` VALUES (281, '韩语');
INSERT INTO `skill` VALUES (282, '技术写作');
INSERT INTO `skill` VALUES (283, '翻译');
INSERT INTO `skill` VALUES (284, '英语语法');
INSERT INTO `skill` VALUES (285, '意大利语');
INSERT INTO `skill` VALUES (286, '捷克语');
INSERT INTO `skill` VALUES (287, '社交网络');
INSERT INTO `skill` VALUES (288, 'Unity 3D');
INSERT INTO `skill` VALUES (289, '用户体验设计');
INSERT INTO `skill` VALUES (290, 'VB.NET');
INSERT INTO `skill` VALUES (291, '视频服务');
INSERT INTO `skill` VALUES (292, '客户支持');
INSERT INTO `skill` VALUES (293, '虚拟助手');
INSERT INTO `skill` VALUES (294, 'Visual Basic');
INSERT INTO `skill` VALUES (295, '配音演员');
INSERT INTO `skill` VALUES (296, '网页搜罗');
INSERT INTO `skill` VALUES (297, '网页搜索');
INSERT INTO `skill` VALUES (298, '网络主机');
INSERT INTO `skill` VALUES (299, '论坛软件');
INSERT INTO `skill` VALUES (300, 'CS-Cart');
INSERT INTO `skill` VALUES (301, '网站设计');
INSERT INTO `skill` VALUES (302, '视窗 Server');
INSERT INTO `skill` VALUES (303, 'Word 处理');
INSERT INTO `skill` VALUES (304, '动画');
INSERT INTO `skill` VALUES (305, '简体中文（中国）');
INSERT INTO `skill` VALUES (306, '学术写作');
INSERT INTO `skill` VALUES (307, '翻译');
INSERT INTO `skill` VALUES (308, 'Logistics');
INSERT INTO `skill` VALUES (309, '商业计划');
INSERT INTO `skill` VALUES (310, 'Intuit快账');
INSERT INTO `skill` VALUES (311, 'C# 编程');
INSERT INTO `skill` VALUES (312, '发布');
INSERT INTO `skill` VALUES (313, 'VoIP');
INSERT INTO `skill` VALUES (314, '视频服务');
INSERT INTO `skill` VALUES (315, 'iPhone');
INSERT INTO `skill` VALUES (316, 'MySQL');
INSERT INTO `skill` VALUES (317, '漫画 与 卡通');
INSERT INTO `skill` VALUES (318, '文案写作');
INSERT INTO `skill` VALUES (319, '论坛发贴');
INSERT INTO `skill` VALUES (320, '代笔');
INSERT INTO `skill` VALUES (321, '校对');
INSERT INTO `skill` VALUES (322, '内容写作');
INSERT INTO `skill` VALUES (323, '研究');
INSERT INTO `skill` VALUES (324, '系统管理');
INSERT INTO `skill` VALUES (325, 'C++编程');
INSERT INTO `skill` VALUES (326, 'Linux');
INSERT INTO `skill` VALUES (327, '电子');
INSERT INTO `skill` VALUES (328, '机器学习（ML）');
INSERT INTO `skill` VALUES (329, 'C 编程');
INSERT INTO `skill` VALUES (330, 'Golang');
INSERT INTO `skill` VALUES (331, '微软');
INSERT INTO `skill` VALUES (332, 'Objective C');
INSERT INTO `skill` VALUES (333, '时尚设计');
INSERT INTO `skill` VALUES (334, '法律');
INSERT INTO `skill` VALUES (335, '电子书');
INSERT INTO `skill` VALUES (336, '视频传播');
INSERT INTO `skill` VALUES (337, 'Red Hat');
INSERT INTO `skill` VALUES (338, '标语');
INSERT INTO `skill` VALUES (339, 'Drupal');
INSERT INTO `skill` VALUES (340, 'JavaScript');
INSERT INTO `skill` VALUES (341, 'HTML5');
INSERT INTO `skill` VALUES (342, 'AJAX');
INSERT INTO `skill` VALUES (343, '数据处理');
INSERT INTO `skill` VALUES (344, 'Excel');
INSERT INTO `skill` VALUES (345, '数据输入');
INSERT INTO `skill` VALUES (346, '网页搜罗');
INSERT INTO `skill` VALUES (347, '网页搜索');
INSERT INTO `skill` VALUES (348, '工程');
INSERT INTO `skill` VALUES (349, '俄语');
INSERT INTO `skill` VALUES (350, '西班牙语');
INSERT INTO `skill` VALUES (351, '视频制作');
INSERT INTO `skill` VALUES (352, 'Word');
INSERT INTO `skill` VALUES (353, 'Pinterest');
INSERT INTO `skill` VALUES (354, '社交网络');
INSERT INTO `skill` VALUES (355, '电子邮箱营销');
INSERT INTO `skill` VALUES (356, '金融研究');
INSERT INTO `skill` VALUES (357, '3D 渲染');
INSERT INTO `skill` VALUES (358, '安卓');
INSERT INTO `skill` VALUES (359, '封面 与 包装');
INSERT INTO `skill` VALUES (360, 'Logo设计');
INSERT INTO `skill` VALUES (361, 'Photoshop 设计');
INSERT INTO `skill` VALUES (362, 'PHP');
INSERT INTO `skill` VALUES (363, 'Joomla');
INSERT INTO `skill` VALUES (364, '用户接口 / IA');
INSERT INTO `skill` VALUES (365, '微软Access');
INSERT INTO `skill` VALUES (366, '网站设计');
INSERT INTO `skill` VALUES (367, 'Photoshop');
INSERT INTO `skill` VALUES (368, 'HTML');
INSERT INTO `skill` VALUES (369, '平面设计');
INSERT INTO `skill` VALUES (370, 'node.js');
INSERT INTO `skill` VALUES (371, 'JSP');
INSERT INTO `skill` VALUES (372, 'Java');
INSERT INTO `skill` VALUES (373, '视频编辑');
INSERT INTO `skill` VALUES (374, '网络营销');
INSERT INTO `skill` VALUES (375, 'PSD转化为HTML');
INSERT INTO `skill` VALUES (376, 'Illustration');
INSERT INTO `skill` VALUES (377, 'jQuery / Prototype');
INSERT INTO `skill` VALUES (378, 'Illustrator');
INSERT INTO `skill` VALUES (379, 'ASP');
INSERT INTO `skill` VALUES (380, '数据库编程');
INSERT INTO `skill` VALUES (381, 'Link Building');
INSERT INTO `skill` VALUES (382, '市场');
INSERT INTO `skill` VALUES (383, '销售');
INSERT INTO `skill` VALUES (384, 'SEO');
INSERT INTO `skill` VALUES (385, '销售线索');
INSERT INTO `skill` VALUES (386, '社会化引擎');
INSERT INTO `skill` VALUES (387, 'J2EE');
INSERT INTO `skill` VALUES (388, 'Delphi');
INSERT INTO `skill` VALUES (389, 'UNIX');
INSERT INTO `skill` VALUES (390, '企业形象');
INSERT INTO `skill` VALUES (391, '生产');
INSERT INTO `skill` VALUES (392, '产品采购');
INSERT INTO `skill` VALUES (393, '自由职业');
INSERT INTO `skill` VALUES (394, '移动应用开发');
INSERT INTO `skill` VALUES (395, 'iPad');
INSERT INTO `skill` VALUES (396, '项目管理');
INSERT INTO `skill` VALUES (397, '视窗桌面');
INSERT INTO `skill` VALUES (398, '软件构架');
INSERT INTO `skill` VALUES (399, '软件测试');
INSERT INTO `skill` VALUES (400, '谷歌地图API');
INSERT INTO `skill` VALUES (401, '网络主机');
INSERT INTO `skill` VALUES (402, '电话销售');
INSERT INTO `skill` VALUES (403, '视窗应用程序接口');
INSERT INTO `skill` VALUES (404, 'Visual Basic');
INSERT INTO `skill` VALUES (405, 'Salesforce.com');
INSERT INTO `skill` VALUES (406, '网站测试');
INSERT INTO `skill` VALUES (407, '工艺美术');
INSERT INTO `skill` VALUES (408, '动态图像');
INSERT INTO `skill` VALUES (409, '3ds Max');
INSERT INTO `skill` VALUES (410, 'AutoCAD');
INSERT INTO `skill` VALUES (411, '客户支持');
INSERT INTO `skill` VALUES (412, '网站管理');
INSERT INTO `skill` VALUES (413, 'Jabber');
INSERT INTO `skill` VALUES (414, '购物车');
INSERT INTO `skill` VALUES (415, 'WordPress');
INSERT INTO `skill` VALUES (416, ' Payroll');
INSERT INTO `skill` VALUES (417, ' 移动应用测试');
INSERT INTO `skill` VALUES (418, ' 体育');
INSERT INTO `skill` VALUES (419, ' 微控制器');
INSERT INTO `skill` VALUES (420, ' 游戏设计');
INSERT INTO `skill` VALUES (421, ' SQL');
INSERT INTO `skill` VALUES (422, ' 法律写作');
INSERT INTO `skill` VALUES (423, ' 研究');
INSERT INTO `skill` VALUES (424, ' 视频服务');
INSERT INTO `skill` VALUES (425, ' 网络管理');
INSERT INTO `skill` VALUES (426, ' PhoneGap');
INSERT INTO `skill` VALUES (427, ' ASP.NET');
INSERT INTO `skill` VALUES (428, ' 网页搜罗');
INSERT INTO `skill` VALUES (429, ' 工业设计');
INSERT INTO `skill` VALUES (430, ' 泰语');
INSERT INTO `skill` VALUES (431, ' 土耳其语');
INSERT INTO `skill` VALUES (432, ' 越南语');
INSERT INTO `skill` VALUES (433, ' 瑞士语');
INSERT INTO `skill` VALUES (434, ' Facebook营销');
INSERT INTO `skill` VALUES (435, ' T恤');
INSERT INTO `skill` VALUES (436, ' 网络主机');
INSERT INTO `skill` VALUES (437, ' 摄影');
INSERT INTO `skill` VALUES (438, ' Visual Basic');
INSERT INTO `skill` VALUES (439, ' WordPress');
INSERT INTO `skill` VALUES (440, ' 购物车');
INSERT INTO `skill` VALUES (441, ' Illustrator');
INSERT INTO `skill` VALUES (442, ' JavaFX');
INSERT INTO `skill` VALUES (443, ' VB.NET');
INSERT INTO `skill` VALUES (444, ' 封面 与 包装');
INSERT INTO `skill` VALUES (445, ' 产品采购');
INSERT INTO `skill` VALUES (446, ' 供应商采购');
INSERT INTO `skill` VALUES (447, ' 视窗电话');
INSERT INTO `skill` VALUES (448, ' Maya');
INSERT INTO `skill` VALUES (449, ' 网站管理');
INSERT INTO `skill` VALUES (450, ' 信息图表');
INSERT INTO `skill` VALUES (451, ' UNIX');
INSERT INTO `skill` VALUES (452, ' Unity 3D');
INSERT INTO `skill` VALUES (453, ' 工艺美术');
INSERT INTO `skill` VALUES (454, ' x86/x64 汇编');
INSERT INTO `skill` VALUES (455, ' YouTube');
